version: "3"
networks: 
  default:
    external:
      name: app
services: 
  redis-node-0:
    image: ${DOCKER_REPO}redis-cluster:${DOCKER_TAG}
    container_name: redis-node-0
    environment:
      REDIS_PORT: '6379'
    ports:
      - '7000:6379'
      - '17000:16379'
  redis-node-1:
    image: ${DOCKER_REPO}redis-cluster:${DOCKER_TAG}
    container_name: redis-node-1
    environment:
      REDIS_PORT: '6379'
    ports:
      - '7001:6379'
      - '17001:16379'
  redis-node-2:
    image: ${DOCKER_REPO}redis-cluster:${DOCKER_TAG}
    container_name: redis-node-2
    environment:
      REDIS_PORT: '6379'
    ports:
      - '7002:6379'
      - '17002:16379'
  redis-node-3:
    image: ${DOCKER_REPO}redis-cluster:${DOCKER_TAG}
    container_name: redis-node-3
    environment:
      REDIS_PORT: '6379'
    ports:
      - '7003:6379'
      - '17003:16379'
  redis-node-4:
    image: ${DOCKER_REPO}redis-cluster:${DOCKER_TAG}
    container_name: redis-node-4
    environment:
      REDIS_PORT: '6379'
    ports:
      - '7004:6379'
      - '17004:16379'
  redis-node-5:
    image: ${DOCKER_REPO}redis-cluster:${DOCKER_TAG}
    container_name: redis-node-5
    environment:
      REDIS_PORT: '6379'
    ports:
      - '7005:6379'
      - '17005:16379'
  redis-cluster-init:
    image: ${DOCKER_REPO}redis-cluster:${DOCKER_TAG}
    container_name: redis-cluster-init
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    environment: 
      INIT_CLUSTER: 'true'
      CLUSTER_REPLICAS: "1"
      REDIS_NODES: redis-node-0:6379,
                   redis-node-1:6379,
                   redis-node-2:6379,
                   redis-node-3:6379,
                   redis-node-4:6379,
                   redis-node-5:6379