version: "3"
networks:
  default:
    external:
      name: app
services: 
  python-base:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
      args:
        VARIANT: "3.9"
        INSTALL_NODE: "false"
    container_name: python-base
    # restart: always
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"